import { useEffect, useRef, useState } from "react"

export default function SearchDropdown() {
    const [searchTerm, setSearchterm] = useState('')
    const [filtered, setFiltered] = useState([])
    const [tags, setTags]= useState([])
    const dropdownRef = useRef(null)
    const [data, _] = useState([
        "Abian",
        "Adventure",
        "Advisor",
        "Aetherborn",
        "Ajani",
        "Alara",
        "Alfava Metraxis",
        "Alicorn",
        "Alien",
        "Ally",
        "Aminatou",
        "Amonkhet",
        "and/or",
        "Androzani Minor",
        "Angel",
        "Angrath",
        "Antausia",
        "Antelope",
        "Apalapucia",
        "Ape",
        "Arcane",
        "Arcavios",
        "Archer",
        "Archon",
        "Arkhos",
        "Arlinn",
        "Armadillo",
        "Art",
        "Artificer",
        "Ashiok",
        "Assassin",
        "Assembly-Worker",
        "Astartes",
        "Atog",
        "Attraction",
        "Aura",
        "Aurochs",
        "Autobot",
        "Avatar",
        "Azgol",
        "Azra",
        "Background",
        "Baddest,",
        "Badger",
        "Bahamut",
        "Barbarian",
        "Bard",
        "Basilisk",
        "Basri",
        "Bat",
        "Bear",
        "Beast",
        "Beaver",
        "Beeble",
        "Beholder",
        "Belenon",
        "Berserker",
        "Biggest,",
        "Bird",
        "Boar",
        "B.O.B.",
        "Bobblehead",
        "Bolas",
        "Bolas's Meditation Realm",
        "Brainiac",
        "Bringer",
        "Brushwagg",
        "Bureaucrat",
        "Byode",
        "Calix",
        "Camel",
        "Capenna",
        "Capybara",
        "Carrier",
        "Cartouche",
        "Case",
        "Cat",
        "Cave",
        "Centaur",
        "Cephalid",
        "Chameleon",
        "Chandra",
        "Chicken",
        "Child",
        "Chimera",
        "Chorus",
        "Citizen",
        "Clamfolk",
        "Class",
        "Cleric",
        "Cloud",
        "Clown",
        "Clue",
        "Cockatrice",
        "Comet",
        "Construct",
        "Contraption",
        "Cow",
        "Coward",
        "Coyote",
        "Crab",
        "Cridhe",
        "Crocodile",
        "C'tan",
        "Curse",
        "Custodes",
        "Cyberman",
        "Cyborg",
        "Cyclops",
        "Dack",
        "Dakkon",
        "Dalek",
        "Daretti",
        "Darillium",
        "Dauthi",
        "Davriel",
        "Deb",
        "Deer",
        "Demigod",
        "Demon",
        "Desert",
        "Designer",
        "Detective",
        "Devil",
        "Dihada",
        "Dinosaur",
        "Djinn",
        "Doctor",
        "Dog",
        "Dominaria",
        "Domri",
        "Donkey",
        "Dovin",
        "Dragon",
        "Drake",
        "Dreadnought",
        "Drone",
        "Druid",
        "Dryad",
        "Duck",
        "Dungeon",
        "Dwarf",
        "Earth",
        "Echoir",
        "Efreet",
        "Egg",
        "Elder",
        "Eldraine",
        "Eldrazi",
        "Elemental",
        "Elemental?",
        "Elephant",
        "Elf",
        "Elk",
        "Ellywick",
        "Elminster",
        "Elspeth",
        "Elves",
        "Employee",
        "Equilor",
        "Equipment",
        "Ergamon",
        "Ersta",
        "Estrid",
        "Etiquette",
        "Eye",
        "Fabacin",
        "Faerie",
        "Ferret",
        "Fiora",
        "Fire",
        "Fish",
        "Flagbearer",
        "Food",
        "Forest",
        "Fortification",
        "Fox",
        "Fractal",
        "Freyalise",
        "Frog",
        "Fungus",
        "Gallifrey",
        "Gamer",
        "Gargantikar",
        "Gargoyle",
        "Garruk",
        "Gate",
        "Giant",
        "Gideon",
        "Gith",
        "Gnoll",
        "Gnome",
        "Goat",
        "Gobakhan",
        "Goblin",
        "God",
        "Golem",
        "Gorgon",
        "Grandchild",
        "Gremlin",
        "Griffin",
        "Grist",
        "Guest",
        "Guff",
        "Gus",
        "Hag",
        "Halfling",
        "Harpy",
        "Hatificer",
        "Head",
        "Hellion",
        "Hero",
        "Hippo",
        "Hippogriff",
        "Homarid",
        "Homunculus",
        "Horror",
        "Horse",
        "Horsehead Nebula",
        "Huatli",
        "Human",
        "Hydra",
        "Hyena",
        "Igpay",
        "Ikoria",
        "Illusion",
        "Imp",
        "Incarnation",
        "Innistrad",
        "Inquisitor",
        "Insect",
        "Inzerva",
        "Iquatana",
        "Ir",
        "Island",
        "Ixalan",
        "Jace",
        "Jackal",
        "Jared",
        "Jaya",
        "Jellyfish",
        "Jeska",
        "Juggernaut",
        "Kaito",
        "Kaladesh",
        "Kaldheim",
        "Kamigawa",
        "Kandoka",
        "Kangaroo",
        "Karn",
        "Karsus",
        "Kasmina",
        "Kavu",
        "Kaya",
        "Kephalai",
        "Key",
        "Killbot",
        "Kinshala",
        "Kiora",
        "Kirin",
        "Kithkin",
        "Knight",
        "Kobold",
        "Kolbahan",
        "Kor",
        "Koth",
        "Kraken",
        "Kylem",
        "Kyneth",
        "Lady",
        "Lair",
        "Lamia",
        "Lammasu",
        "Leech",
        "Lesson",
        "Leviathan",
        "Lhurgoyf",
        "Licid",
        "Liliana",
        "Lizard",
        "Lobster",
        "Locus",
        "Lolth",
        "Lorwyn",
        "Lukka",
        "Luvion",
        "Mammoth",
        "Manticore",
        "Mars",
        "Master",
        "Masticore",
        "Mercadia",
        "Mercenary",
        "Merfolk",
        "Metathran",
        "Mime",
        "Mine",
        "Minion",
        "Minotaur",
        "Minsc",
        "Mirrodin",
        "Mite",
        "Moag",
        "Mole",
        "Monger",
        "Mongoose",
        "Mongseng",
        "Monk",
        "Monkey",
        "Moon",
        "Moonfolk",
        "Mordenkainen",
        "Mount",
        "Mountain",
        "Mouse",
        "Mummy",
        "Muraganda",
        "Mutant",
        "Myr",
        "Mystic",
        "Naga",
        "Nahiri",
        "Narset",
        "Nastiest,",
        "Nautilus",
        "Necron",
        "Necros",
        "Nephilim",
        "New Earth",
        "New Phyrexia",
        "Nightmare",
        "Nightstalker",
        "Niko",
        "Ninja",
        "Nissa",
        "Nixilis",
        "Noble",
        "Noggle",
        "Nomad",
        "Nymph",
        "Octopus",
        "Ogre",
        "Oko",
        "Ooze",
        "Orc",
        "Orgg",
        "Otter",
        "Ouphe",
        "Outside Mutter's Spiral",
        "Ox",
        "Oyster",
        "Pangolin",
        "Paratrooper",
        "Peasant",
        "Pegasus",
        "Penguin",
        "Performer",
        "Pest",
        "Phelddagrif",
        "Phoenix",
        "Phyrexia",
        "Phyrexian",
        "Pilot",
        "Pirate",
        "Plains",
        "Plant",
        "Pony",
        "Porcupine",
        "Possum",
        "Power-Plant",
        "Powerstone",
        "Praetor",
        "Primarch",
        "Processor",
        "Proper",
        "Pyrulea",
        "Quintorius",
        "Rabbit",
        "Rabiah",
        "Raccoon",
        "Ral",
        "Ranger",
        "Rat",
        "Rath",
        "Ravnica",
        "Rebel",
        "Reflection",
        "Regatha",
        "Rhino",
        "Rigger",
        "Robot",
        "Rogue",
        "Rowan",
        "Rune",
        "Sable",
        "Saga",
        "Saheeli",
        "Salamander",
        "Samurai",
        "Samut",
        "Sarkhan",
        "Satyr",
        "Scarecrow",
        "Scientist",
        "Scorpion",
        "Scout",
        "Segovia",
        "Serpent",
        "Serra",
        "Serra’s Realm",
        "Shade",
        "Shadowmoor",
        "Shaman",
        "Shandalar",
        "Shapeshifter",
        "Shark",
        "Sheep",
        "Shenmeng",
        "Ship",
        "Shrine",
        "Siege",
        "Siren",
        "Sivitri",
        "Skaro",
        "Skeleton",
        "Slith",
        "Sliver",
        "Sloth",
        "Slug",
        "Snail",
        "Snake",
        "Soldier",
        "Soltari",
        "Sorin",
        "Spacecraft",
        "Spawn",
        "Specter",
        "Spellshaper",
        "Sphere",
        "Sphinx",
        "Spider",
        "Spike",
        "Spirit",
        "Sponge",
        "Spy",
        "Squid",
        "Squirrel",
        "Starfish",
        "Surrakar",
        "Svega",
        "Swamp",
        "Synth",
        "Szat",
        "Tamiyo",
        "Tarkir",
        "Tasha",
        "Teferi",
        "Teyo",
        "Tezzeret",
        "Thalakos",
        "The",
        "The Abyss",
        "The Dalek Asylum",
        "The Library",
        "Theros",
        "Thopter",
        "Thrull",
        "Tibalt",
        "Tiefling",
        "Time",
        "Time Lord",
        "Tower",
        "Townsfolk",
        "Trap",
        "Treasure",
        "Treefolk",
        "Trenzalore",
        "Trilobite",
        "Troll",
        "Turtle",
        "Tyranid",
        "Tyvar",
        "Ugin",
        "Ulgrotha",
        "Unicorn",
        "Unknown Planet",
        "Urza",
        "Urza's",
        "Valla",
        "Vampire",
        "Vampyre",
        "Varmint",
        "Vedalken",
        "Vehicle",
        "Venser",
        "Viashino",
        "Villain",
        "Vivien",
        "Volver",
        "Vraska",
        "Vronos",
        "Vryn",
        "Waiter",
        "Wall",
        "Walrus",
        "Wanderer",
        "Warlock",
        "Warrior",
        "Weird",
        "Werewolf",
        "Whale",
        "Wildfire",
        "Will",
        "Windgrace",
        "Wizard",
        "Wolf",
        "Wolverine",
        "Wombat",
        "Worm",
        "Wraith",
        "Wrenn",
        "Wrestler",
        "Wurm",
        "Xenagos",
        "Xerex",
        "Yanggu",
        "Yanling",
        "Yeti",
        "Zariel",
        "Zendikar",
        "Zhalfir",
        "Zombie",
        "Zubera"
    ])


    useEffect(() => {
        dropdownRef.current = new bootstrap.Dropdown(document.getElementById('ddown'))
        return () => dropdownRef.current = null
    }, [])


    useEffect(() => {
        const filteredData = data.filter(type => type.toLowerCase().includes(searchTerm.toLowerCase()))
        setFiltered(filteredData)
    }, [searchTerm])

    function onFocus() {
        dropdownRef.current.show()
    }

    function onBlur(e) {
        const elem = e.relatedTarget
        console.log(elem)
        if (!elem?.classList.contains('dropdown-item')) {
            dropdownRef.current.hide()
        }
    }

    function onClick(e) {
        const tag = <div className="badge m-1" >{e.target.innerText}</div>
        setTags([...new Set(tags), tag])
        dropdownRef.current.hide()
    }

    const renderTypes = filtered.map(item =>
        <li key={item}><a onClick={onClick} class="dropdown-item" href="#">{item}</a></li>)

    return (
        <div className="search-dropdown">
            <div className="input-group mb-2">
                <button className="btn search-btn" disabled>
                    <img id="search-icon" src="/icons/search.svg"></img>
                </button>
                <input value={searchTerm} onChange={(e) => setSearchterm(e.target.value)}
                    onBlur={onBlur}
                    onFocus={onFocus}
                    placeholder={'Subtype...'} type="text" className="form-control search-input"></input>
            </div>

            <div id="ddown" class="dropdown">
                <div data-bs-toggle="dropdown">
                    </div>

                <ul class="dropdown-menu">
                    {renderTypes}
                </ul>
            </div>
            <div className="tag-zone">
                {tags}
            </div>
        </div>

    )

}